#개발용
# spring:
#   servlet:
#     multipart:
#       max-file-size: 100MB #파일 최대 용량
#       max-request-size: 200MB #받을 파일 용량
server:
  port: 8080

  servlet:
    session:
      timeout: 1m

spring:
  # JPA logging을 위한 추가 설정 -> yml 버전
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  #DB datasource
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://data.newlecture.com:3306/rlanddb?serverTimezone=Asia/Seoul&amp;characterEncoding=UTF-8
    username: rland
    password: 20231110





logging:
  level:
    kr:
      co:
        rland:
          api:
            repository: TRACE



    
  
